# coding: utf8
GLOBAL_URL = "https://doublej.herokuapp.com"
ERR_PASSWORD = "Invalid password or username"
ERR_UNAUTH = "Please login to continue"
ERR_BLANK = "data incomplete"
ERR_EMAIL = "invalid email"
ERR_FORM = 'form must be fulfilled'
ERR_UNI_USER = "username already exists, choose another one"
ERR_UNI_POST = "unique post"
ERR_NODATA = "unable to find this query"
ERR_SERVOR = "internal servor error"
ERR_NOPOST = "Vous n'avez pas d'annonce affichée"
ERR_404 = "Cette page n'existe pas"
ERR_RESERVATION = "Unable to reserve this room"

MSG_MAIL_SENT_RECOVERY = "Recover your password in your email "
MSG_MAIL_RECOVER_SUBJECT = "Recover your password"
MSG_MAIL_RECOVER_BODY = "login with this password : "
MSG_MAIL_REGISTER_SUCCESS_SUBJECT = "You have succesfully registered to BookingExpert. "
MSG_MAIL_REGISTER_SUCCESS_BODY = "Thank you very much. Feel free to ask any question."
MSG_MAIL_RESERVATION_SUCCESS_SUBJECT = "You have succesfully reserved a room. "
MSG_MAIL_RESERVATION_SUCCESS_BODY = "Thank you very much. Reservstions details."                               